---
title: "Social Dominance Analysis"
author: "Nora Reinhardt, Josie Peterburs, and Dr. Gregory Matthews"
format: 
  html:
    self-contained: true
    embed-resources: true
editor: visual
execute:
  echo: false
  eval: true
  warning: false
---

```{r, include=FALSE}
library(foreign)
library(tidyverse)
library(gridExtra)

#dat <- as.data.frame(read.spss("/Users/cleanedorymatthews/Dropbox/social_dominance/HierarchyNoDS 02.16.sav"))
# dat <- as.data.frame(read.spss("/Users/noral/OneDrive/Desktop/CDSC/social dominance new/HierarchyNoDS 02.16.sav"))
dat <- as.data.frame(read.spss("C:/Users/gigip/personal/CDSC/social_dominance/HierarchyNoDS 02.16.sav"))

# view cismen columns
dat %>% select(cismen_1:cismen_4, cismen_competence) %>% na.omit() %>% head()

#1-4: Competence: These get averaged together to get a competence score
#5-8: Warmth: These get averaged together for a warmth score. 
#cluster these: small <- dat %>% select(cismen_competence:crohns_warmth)
```

```{r}
# get rid of extra words in 1 and 5 rating 
  # cols1to8 is includes each column for given group
getnames <- dat %>% select(cismen_1:crohns_8)
colnametochange  <-  colnames(getnames)
cols1to8 <- dat %>%
  mutate(across(all_of(colnametochange), ~ as.numeric(substr(., 1, 1)))) %>% 
  select(cismen_1:crohns_8)

# small is the means for scores 1-4 and 5-8 for each group
  # clean agcleanedates to be the overall mean for competence and warmth for each group
small <- dat %>% 
  mutate(across(all_of(colnametochange), ~ as.numeric(substr(., 1, 1)))) %>%
  select(cismen_competence:crohns_warmth)

clean <- as.data.frame(matrix(apply(small, 2, mean, na.rm = TRUE) , ncol = 2, byrow = TRUE))
names(clean) <- c("comp", "warmth")
clean$var <- names(apply(small, 2, mean, na.rm = TRUE))[seq(1,92,2)]

cleaned <- clean %>% mutate(var = str_remove(var,"_competence")) 
```


```{r}
clean %>% mutate(var = str_remove(var,"_competence")) %>% 
  ggplot(aes(x = warmth, y= comp)) + 
  geom_point() + 
  geom_label(aes(label = var)) + 
  xlim(c(1,5)) + ylim(c(1,5)) +
  ggtitle('Average Warmth and Competence Score for Each Group') +
  theme(plot.title = element_text(hjust = 0.5))
```

### Clustering Groups

```{r}
# Clustering
set.seed(1234)
cleaned$clust <- kmeans(cleaned[,1:2], 4, nstart =10)$cluster
cleaned %>%  ggplot(aes(x = warmth, y = comp, color = as.factor(clust))) +
  geom_point() +
  xlim(1,5) + ylim(1,5) + 
  stat_ellipse(type = "norm")

groups <- cleaned %>% arrange(clust)

knitr::kable(groups,
caption = "Clusters for Each Group from K-Means Clustering")
```

```{r, eval=FALSE}
# figure out number of clusters
# Use map_dbl to run many models with varying value of k (centers)

tot_withinss <- c()
for (k in 1:10){
  model <- kmeans(x = greg[,1:2], centers = k)
  tot_withinss[k] <- model$tot.withinss
}

# Generate a data frame containing both k and tot_withinss
elbow_df <- data.frame(
  k = 1:10,
  tot_withinss = tot_withinss
)
# Plot the elbow plot
ggplot(elbow_df, aes(x = k, y = tot_withinss)) +
  geom_line() + geom_point()+
  scale_x_continuous(breaks = 1:10) + theme_bw()

# four clusters
```

# Bar Charts for Ratings in Categories 1-4 and 5-8 for Each Group

```{r}
# pivot longer
boxes <- cols1to8 %>% pivot_longer(cols = cismen_1:crohns_8, names_to = "group", values_to = "score") %>% drop_na()
boxes1 <- boxes %>% group_by(group, score) %>% summarize(count = n()) %>% 
  mutate(score = factor(score, levels = c(5, 4, 3, 2, 1)))

# all group names
groups <- cleaned %>% select(var) %>% list()
```

```{r}
make_graph <- function(x = 'cismen'){
  boxes1 %>% filter(grepl(x, group)) %>% 
  separate_wider_delim(group, "_", names = c(NA, "group")) %>% 
  ggplot(aes(x = group, y = count, fill = as.factor(score))) + 
  geom_bar(position = "fill", stat = "identity") +
  scale_fill_discrete(name = "Rating") + 
  ggtitle(x) +
  theme(plot.title = element_text(hjust = 0.5))
}

plot_list <- list()

for (i in unique(cleaned$var)){
  plot_list[[i]] <- make_graph(i)
}

plot_list
```
